### PR TITLE
More prominent formatting of testing snippet used

### PR DESCRIPTION
**Pull request by NOtherDev**
This commit changes the way testing snippet is displayed. Instead of "function() { window.Accelerometer}" formatted as code there is either green or red bar with the test property only, i.e. "window.Accelerometer".

### CODE REVIEW

**Comment by michalczukm** [comment]
Let me check how it looks now, without syntax colouring by Prism

**Comment by NOtherDev** [comment]
Sure. These are one-liners, so my gut feeling is that this syntax coloring isn't needed. But I'm biased from how I do it on whatwebcando.today 😀

**Comment by michalczukm** [comment]
I checked it, and when test text is longer its not adjusting width:
image



Also, Its super subjective - but I like the current short form, without adding extra space for `function test()`. We don't want user to scroll at all (in most cases :) )

**Comment by NOtherDev** [comment]
About the form, I agree that `function test()` is useless and actually my intention was to remove it and leave only the actual test code function body, i.e. `window.Notification`. I changed the approach now, there are pretty complex regexes running now to get rid of the function declaration parts.

About the line breaking – thanks for the catch, I obviously haven't checked that case. Now I added zero-width spaces after dots so it should break fine.

**Pull request merged**
